### ISSUE TITLE
Missing 'public/js/util/browser.js' file in user-accounts example

### ISSUE THREAD

**Issue by jakepruitt** [rjrodger/seneca-examples#9]
In the file [/user-accounts/public/single.html on line 5](https://github.com/rjrodger/seneca-examples/blob/master/user-accounts/public/single.html#L5), there is a reference to a file that should be located at /user-accounts/public/js/util/browser.js.  This file does not exist, as can be seen in 404 error on the single.html page.

![screenshot_071014_052844_pm](https://cloud.githubusercontent.com/assets/5084263/3541752/43335af6-084f-11e4-8d37-e9ece40d5dad.jpg)

**Comment by rjrodger** [comment]
this is not longer relevant
